language: java
jdk:
  - oraclejdk8
before_install:
  - pip install --user codecov
notifications:
  email:
    recipients:
      - santiago.skyline@gmail.com
    on_success: always
    on_failure: always
after_success:
  - codecov
