language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - santiago.skyline@gmail.com
    on_success: always
    on_failure: always
after_success:
  - bash <(curl -s https://codecov.io/bash)
